enabled: true
top_level_version: false
google_analytics_code: null
home_url: null
github:
  position: top
  icon: null
  tree: null
default_taxonomy_category: docs
style: default
streams:
  schemes:
    theme:
      type: ReadOnlyStream
      prefixes:
        '': ['themes://learn2-git-sync', 'themes://learn2']
enable_doc_versioning: false
hide_site_title: false
